### ISSUE TITLE
Apply grkmisc::pretty_num to negative numbers

### ISSUE THREAD

**Issue by cararthompson** [GerkeLab/grkmisc#8]
Hi! First off, thanks for sharing this package. I've used the pretty_num() function a lot in data visualisations. 

I just tried to use it in a plot which contained negative numbers and noticed it didn't work. 

```
> grkmisc::pretty_num(11000)
[1] "11k"
> grkmisc::pretty_num(-11000)
[1] "-11000"
```

Is this deliberate? Would there be any interest in allowing it to accept negative numbers? 

Using grkmisc_0.1.3 with R 4.1.2

Thanks!

**Comment by cararthompson** [comment]
Hi @tgerke and @gadenbuie! I often use this function in dataviz, but a few clients have struggled to install the package recently. I was hoping it had made it across to {epoxy} but I didn't spot it there.

If it is there, can you keep me right? If it isn't, would you have any objections to me creating a variant to allow it to work with negative numbers and adding it to my {verbaliseR} package? Thanks!

**Comment by gadenbuie** [comment]
Hi @cararthompson, I'm glad you've found this function and package helpful! You're welcome to lift `pretty_num()` or anything else from this package into your own package if you want.

I should point out that I've since discovered the `scale_cut` argument of `scales::number()` and that's _probably_ what I would use these days.

```r
scales::number(11000, scale_cut = scales::cut_long_scale())
#> [1] "11K"

scales::number(-11000, scale_cut = scales::cut_long_scale())
#> [1] "-11K"
```

**Comment by cararthompson** [comment]
Ah, thank you! I'll look into that. Very grateful for the tip!

**Comment by cararthompson** [comment]
This is great - you've saved me a bunch of work updating a package and avoided me creating an extra dependency!

My initial reaction was that I missed the digit after the decimal point, but the `accuracy` argument takes care of that. 

```
scales::number(-34500000, accuracy = 0.1, scale_cut = scales::cut_long_scale())
"-34.5M"
```

To make it drop the zero, we need to use  `drop0trailing = TRUE`, which gets passed on to `base::format()`: 

```
scales::number(-34000000, accuracy = 0.1, scale_cut = scales::cut_long_scale())
# "-34.0M"

scales::number(-34000000, accuracy = 0.1, drop0trailing = TRUE, trim = FALSE, scale_cut = scales::cut_long_scale())
# "-34M"
```

**Comment by cararthompson** [comment]
I wrote up a post about this. Thanks for your help in figuring out the best way to do this!

https://www.cararthompson.com/posts/2024-01-30-formatting-numbers-in-r/2024-01-30_formatting-numbers-in-r
